### ISSUE TITLE
Selecting the v1 ledger (testnet/production/etc) should be configurable

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-kms#18]
Currently, the DID resolver used here has the V1 testnet ledger as hardcoded -- this should be configurable.

**Comment by mattcollier** [comment]
After speaking with longley, the approach we want to take here is to implement a bedrock-foo wrapper around did-io for the purpose of configuring did-io.  There is a previous effort along these lines here:

https://github.com/digitalbazaar/bedrock-did-client

There could be a new revision of that library, or a new thing could be created, but it should:
- Provide/reuse some plugin architecture for specifying DID methods to be used.
- Provide the ability to configure various did methods. In the case of did-veres-one, one configuration option would have to do with whether to connect to mainnet or testnet.

**Comment by mattcollier** [comment]
Setup new bedrock-did-io module: https://github.com/digitalbazaar/bedrock-did-io/issues/1

Once that's ready it should be used here.

**Comment by dlongley** [comment]
bedrock-did-io is being used here now, closing.
