### ISSUE TITLE
Remove `forceConstruct` option used with DID resolver for v1 DIDs

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-kms#19]
Some other kind of caching mechanism should be used instead of erroneously forcing v1 DIDs to always be constructed vs. hitting the ledger.

**Comment by mattcollier** [comment]
This is also related to https://github.com/digitalbazaar/bedrock-did-io/issues/1

**Comment by JSAssassin** [comment]
Closing. This has been implemented c9789e9
