### ISSUE TITLE
AllowedHost as an array revisited

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-kms#33]
We have identified a need to allow a single KMS to service multiple host names.  Namely, a hostname of `localhost:18443` that represents traffic originating from the bedrock back-end, and `localhost:9xxx` (Karma) which represents traffic originating from a browser front-end.  The keystoreIds generating in the KMS stack are based on the `req.host` which will contain the two values I've enumerated.

https://github.com/digitalbazaar/bedrock-kms/blob/master/lib/index.js#L28-L47

So currently, there is a deprecated `allowedHosts` config that used to support this feature.  

Should this, and how should this be reimplemented?

**Comment by dlongley** [comment]
So I know that we've identified a need to have a single system hit more than one KMS. But is the reverse true? In dev/testing mode we might have to do things to combine two separate KMS systems into one via hackish configurations, but that may be a better outcome than increasing potential attack surface by allowing KMS systems to accept requests from multiple hosts.

**Comment by dlongley** [comment]
This has been replaced with the `ipAllowList` feature. Closing.
