### ISSUE TITLE
Can keystore `config.id` be binary instead of URL?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-kms#45]
A modern keystore from the `kms-keystores` collection is below.  Does `config.id` need to be string/URL or could it be just the binary representation of the multicodec encoded bytes `z1AEUHNxZHejcLGtvQTRUQZCt`?

In addition to potential space savings, I wonder if it would aid in our ability to be host agnostic.  This is in connection with how we might address API versioning.  Suggestions included differing subdomains or URL path elements, in either case, using URLs for IDs seems challenging.

```
{
	"_id" : ObjectId("615e184343d2f81b5c360be6"),
	"meta" : {
		"created" : 1633556547996,
		"updated" : 1633556547996
	},
	"config" : {
		"id" : "https://kms.qa.veres.app/kms/keystores/z1AEUHNxZHejcLGtvQTRUQZCt",
		"meterId" : "https://meter.qa.veres.app/meters/zV2wZh7G61vwMPk2PVuSC1L",
		"sequence" : 0,
		"controller" : "did:key:z6MkuxGtL8WDBLuLdrDeP8JTQMV37AKUEDNX5gzUrD8RaHHJ",
		"kmsModule" : "ssm-v1",
		"ipAllowList" : [
			"0.0.0.0/0"
		],
		"referenceId" : "primary"
	}
}
```

**Comment by dlongley** [comment]
Closing as this is unlikely to change now. That doesn't rule out a future change, of course, but it doesn't seem to be a priority and this issue is more than a year old now.
